### ISSUE TITLE
Run errors

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [SCANL/swum_project#4]
When i run the SWUM_words, there has been the following errors

What I used as input file is` ./Examples/Die.xml`

**Comment by XiaoXiaoYi123** [comment]
When i run the SWUM_words, there has been the following errors

What I used as input file is` ./Examples/Die.xml`



`Traceback (most recent call last):
  File "swum_words.py", line 435, in <module>
    parser.parse(str(sys.argv[1]))
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/home/builder/tkoch/workspace/python_1648536129212/work/Modules/pyexpat.c", line 471, in EndElement
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "swum_words.py", line 294, in endElement
    self.className, "class", '', self.xmlResult, False)
  File "swum_words.py", line 138, in XMLWriter
    self.PartOfSpeechTag(definedName, identifierTag)
  File "swum_words.py", line 88, in PartOfSpeechTag
    self.dictPOS[currentContent] = nltk.pos_tag(self.text)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/tag/__init__.py", line 165, in pos_tag
    tagger = _get_tagger(lang)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/tag/__init__.py", line 107, in _get_tagger
    tagger = PerceptronTagger()
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 167, in __init__
    find("taggers/averaged_perceptron_tagger/" + PICKLE)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/XiaoxiaoYi/anaconda3/envs/SWUM/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
`
